name: Build tagged image

on:
  push:
    tags:
    tags-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          docker buildx build --push \
          --tag androw/caddy-security:${GITHUB_REF/refs\/tags\//} \
          --platform linux/amd64,linux/arm/v7,linux/arm64 .
